### PR TITLE
Clean up of scripts and instructions

### PR DESCRIPTION
**Pull request by tomhollander**
Changes include:

- Removing the getProjects function, since project data is now returned in the invoices
- Tidying up names of functions
- Changing references to "Realm" to "App Services"
- Updating Charts instructions to align with recent product updates.

### CODE REVIEW

**Comment by simongodb** [comment]
Can log into the AppService app but cannot push the app. 
Getting error: "push failed: invalid event processor config for trigger 'getAllTrigger', function 'getAll' does not exist"

**Comment by tomhollander** [comment]
I already did rename the function and updated the trigger accordingly. Did you start completely from scratch? I did test and was able to deploy.

**Comment by tomhollander** [comment]
@simongodb Looks like git on Windows didn't pick up the filename case change as worthy as pushing. I've addressed this - can you please retest?

**Comment by simongodb** [comment]
Working fine with the renamed functions.

**Pull request merged**
